version: '3'
services:
  redis:
    image: 'redis:alpine'
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_USER: 'human'
      POSTGRES_PASSWORD: 'human'
      POSTGRES_DB: 'humantest'
  api:
    build: .
    environment:
      NODE_ENV: test
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      PORT: 80
      GATEWAY_SECRET: 'TODO'
      GATEWAY_VERSION: '1.0'
      GATEWAY_PG_URL: 'postgresql://human:human@postgres:5432/humantest'
      GATEWAY_PG_READER_URL: 'postgresql://human:human@postgres:5432/humantest'
      GATEWAY_REDIS_SESSION_URL: 'redis://redis:6379'
      GATEWAY_REDIS_CACHE_URL: 'redis://redis:6379'
      GATEWAY_REDIS_LIMITER_URL: 'redis://redis:6379'
      KAFKA_PRODUCER_URL: ''
      AWS_OPERATOR_ACCESS_ID: 'TODO'
      AWS_OPERATOR_ACCESS_SECRET: ''
      AWS_SES_REGION: 'eu-west-1'
      AWS_S3_REGION: 'ap-southeast-1'
      MESSAGE_BIRD_SECRET: ''
    depends_on:
      - redis
      - postgres
    ports:
      - 80:80
    command: "npm test"
