version: '3'
services:
  redis:
    image: 'redis:alpine'
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_USER: 'human'
      POSTGRES_PASSWORD: 'human'
      POSTGRES_DB: 'humandev'
  api:
    build: .
    environment:
      NODE_ENV: development
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      PORT: 3003
      GATEWAY_SECRET: 'TODO'
      GATEWAY_VERSION: '1.0'
      GATEWAY_PG_URL: 'postgres://human:human@localhost:5432/humandev'
      GATEWAY_PG_READER_URL: 'postgres://human:human@localhost:5432/humandev'
      GATEWAY_REDIS_SESSION_URL: 'redis://redis:6379'
      GATEWAY_REDIS_CACHE_URL: 'redis://redis:6379'
      GATEWAY_REDIS_LIMITER_URL: 'redis://redis:6379'
      KAFKA_PRODUCER_URL: ''
      AWS_OPERATOR_ACCESS_ID: 'TODO'
      AWS_OPERATOR_ACCESS_SECRET: ''
      AWS_SES_REGION: 'eu-west-1'
      AWS_S3_REGION: 'ap-southeast-1'
      MESSAGE_BIRD_SECRET: ''
    depends_on:
      - postgres
      - redis
    expose:
      - 3003
    ports:
      - 3003:3003
    volumes:
      - .:/api
    command: /api/scripts/entrypoint.sh
