version: '3'
services:
  redis:
    image: 'redis:alpine'
  api:
    build: .
    ports:
     - 80:80
    environment:
      NODE_ENV: production
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      PORT: 80
      GATEWAY_SECRET: 'TODO'
      GATEWAY_VERSION: '1.0'
      GATEWAY_PG_URL: ''
      GATEWAY_PG_READER_URL: ''
      GATEWAY_REDIS_SESSION_URL: ''
      GATEWAY_REDIS_CACHE_URL: ''
      GATEWAY_REDIS_LIMITER_URL: ''
      KAFKA_PRODUCER_URL: ''
      AWS_OPERATOR_ACCESS_ID: 'TODO'
      AWS_OPERATOR_ACCESS_SECRET: ''
      AWS_SES_REGION: 'eu-west-1'
      AWS_S3_REGION: 'ap-southeast-1'
      MESSAGE_BIRD_SECRET: ''
    depends_on:
      - redis
