version: '3.5'
services:
  redis:
    container_name: redis
    image: 'redis:alpine'
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
  postgres:
    container_name: postgres
    image: 'postgres:10.6'
    environment:
      POSTGRES_USER: 'human'
      POSTGRES_PASSWORD: 'human'
      POSTGRES_DB: 'humandev'
    ports:
      - 5432:5432
